default['symfony']['apps_base_dir'] = '/var/www/html'
default['symfony']['myapp']['branch'] = 'master'
default['symfony']['app_name'] = 'serverexpose'
default['symfony']['web_server']= 'www-data'
default['symfony']['vhost'] = 'serverexpose.com'
default['symfony']['ssl']['versions'] = 'TLSv1.2'
default['symfony']['ssl']['cert_path'] = '/etc/nginx/ssl/'
default['symfony']['php-fpm']['socket'] = '/run/php/php7.0-fpm.sock'
